#!/bin/bash

build() {
    pandoc \
    -V margin-top=15 \
    -V margin-left=17.7 \
    -V margin-right=17.5 \
    -V margin-bottom=15 \
    -c resume.css \
    -t html5 \
    -o resume.pdf \
    resume.md
}

build