#!/bin/bash

build() {
    ./lib/pandoc-2.9.2.1/bin/pandoc \
        --pdf-engine=$PWD"/lib/wkhtmltopdf" \
        --variable=margin-top=15 \
        --variable=margin-left=17.7 \
        --variable=margin-right=17.5 \
        --variable=margin-bottom=15 \
        --css=resume.css \
        --from=markdown \
        --to=html5 \
        --output=resume.pdf \
        resume.md
}

build
